source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'AhNetManagerDemo' do
  ##pod 'NETManager', :path => '../'
  pod 'AFNetworking', '~> 3.0'
  pod 'MJExtension', '~> 3.0.13'
  pod 'MBProgressHUD', '~> 1.0.0'
end
